name: Run JUnit CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  automation-JUnit:
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v3 

      - name: Set up JDK 21
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '21'  
          distribution: 'temurin'  

      - name: Setup Chrome with extra capabilities
        uses: browser-actions/setup-chrome@v1.4.0
        with:
          chrome-version: latest 

      # Setup Gradle Wrapper
      - name: Setup Gradlew
        run: |
          chmod +x gradlew 

      - name: Run Tests
        run: ./gradlew clean test  

      - name: Archive Test Result
        uses: actions/upload-artifact@v4.5.0
        if: always()
        with:
          name: Cucumber Report
          path: reports 


